# Site settings
title: Hyoungjunn Lim blog
email: 
description: "Backend Engineer."
baseurl: ""
url: "http://hyoungjunn.github.io"
twitter_username: Hotfirebulldog
github_username:  hyoungjunn

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
