# Site settings
title: Hyungjunn Lim blog
email: 
description: "Backend Engineer."
baseurl: ""
url: "http://hyungjunn.github.io"
twitter_username: Hotfirebulldog
github_username:  hyungjunn

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
